### ISSUE TITLE
Installation error - systemsbio

### ISSUE THREAD

**Issue by Deepak-Balamurali** [frankRuehle/systemsbio#1]
Hi,

I'm having trouble installing the tool on my system - I've just used the commands as instructed, but the error output indicates there's a package "beadarray" missing. Cold you kindly suggest how this can be fixed? Thanks. 

P.S. Have attached the console log for your reference. 
[Console-log.txt](https://github.com/frankRuehle/systemsbio/files/5182262/Console-log.txt)

**Comment by frankRuehle** [comment]
Hi Deepak,
that just means you need to install the package "beadarray" first. You'll find it here: https://www.bioconductor.org/packages/release/bioc/html/beadarray.html
I have also moved beadarray now from the Suggests to the Depends field, so it will be installed automatically when installing systemsbio.
Cheers, Frank

**Comment by Deepak-Balamurali** [comment]
> Hi Deepak,
> that just means you need to install the package "beadarray" first. You'll find it here: https://www.bioconductor.org/packages/release/bioc/html/beadarray.html
> I have also moved beadarray now from the Suggests to the Depends field, so it will be installed automatically when installing systemsbio.
> Cheers, Frank

Thank you very much, I'll try this now.
